
server:
  port: 8000
  
  
spring:
  application:
    name: KULZ-CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mapoulo/KULZ-DEV-CLOUD-CONFIG/blob/main/application.yml
          clone-on-start: true      
